"""add_time_create_update

Revision ID: 0268251b90a3
Revises: 19f2cc44d306
Create Date: 2022-05-20 17:38:02.561094

"""
from alembic import op
import sqlalchemy as sa
from app.db.structure_of_db import session
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0268251b90a3'
down_revision = '19f2cc44d306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('changes',
    sa.Column('changes_id', sa.Integer(), nullable=False),
    sa.Column('date_of_changes', sa.DateTime(), nullable=True),
    sa.Column('table_changes', sa.String(length=50), nullable=True),
    sa.Column('column_changes', sa.String(length=50), nullable=True),
    sa.Column('old_values', sa.Text(), nullable=True),
    sa.Column('new_values', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('changes_id')
    )
    op.add_column('comments', sa.Column('date_create', sa.DateTime(), nullable=True))
    op.add_column('comments', sa.Column('date_update', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('date_create', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('date_update', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('date_create', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('date_update', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('date_create', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('date_update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_update')
    op.drop_column('users', 'date_create')
    op.drop_column('tasks', 'date_update')
    op.drop_column('tasks', 'date_create')
    op.drop_column('projects', 'date_update')
    op.drop_column('projects', 'date_create')
    op.drop_column('comments', 'date_update')
    op.drop_column('comments', 'date_create')

    op.drop_table('changes')
    # ### end Alembic commands ###
