"""rework date input

Revision ID: 0b53df33a4db
Revises: e90954862b06
Create Date: 2022-04-13 15:53:03.195515

"""
from pprint import pprint
from datetime import datetime
from alembic import op
import sqlalchemy as sa
from app.db.structure_of_db import session, User
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0b53df33a4db'
down_revision = 'e90954862b06'
branch_labels = None
depends_on = None

conn = op.get_bind()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    users_date_stmt = sa.select(User.user_id, User.date_of_input).where(User.date_of_input != None,
                                                                        User.date_of_input != "today")
    users_date = conn.execute(users_date_stmt).fetchall()

    op.drop_column("users", "date_of_input")
    with op.batch_alter_table("users") as batch_op:
        batch_op.add_column(sa.Column("date_of_input", sa.DateTime, nullable=True, default=None))
    for user_id, user_date in users_date:

        bd_data = datetime.strptime(user_date, "%d.%m.%Y").isoformat()
        stmt = sa.update(User).where(User.user_id == user_id).values(date_of_input=bd_data)
        conn.execute(stmt)

    # ### end Alembic commands ###


def downgrade():
    users_date_stmt = sa.select(User.user_id, User.date_of_input).where(User.date_of_input != None)
    users_date = conn.execute(users_date_stmt).fetchall()

    op.drop_column("users", "date_of_input")
    with op.batch_alter_table("users") as batch_op:
        batch_op.add_column(sa.Column("date_of_input", sa.String(15), default="today"))

    for _ in conn.execute(sa.select(User)).fetchall():
        stmt = sa.update(User).values(date_of_input="today")
        conn.execute(stmt)

    for user_id, user_date in users_date:
        bd_data = user_date.strftime("%d.%m.%Y")
        stmt = sa.update(User).where(User.user_id == user_id).values(date_of_input=bd_data)
        conn.execute(stmt)
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
