"""change task_ws_id to int

Revision ID: 0c7340e37708
Revises: 4c9dbd6d8dcc
Create Date: 2022-03-21 15:39:33.493365

"""
from pprint import pprint

from alembic import op
import sqlalchemy as sa
from app.db.structure_of_db import session, Task

# revision identifiers, used by Alembic.
revision = '0c7340e37708'
down_revision = '4c9dbd6d8dcc'
branch_labels = None
depends_on = None

conn = op.get_bind()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # pass
    tasks_parents_stmt = sa.select(Task.task_id, Task.task_ws_id)
    tasks_parents = conn.execute(tasks_parents_stmt).fetchall()

    op.drop_column("tasks", "task_ws_id")
    with op.batch_alter_table("tasks") as batch_op:
        batch_op.add_column(sa.Column("task_ws_id", sa.Integer(), nullable=True))

    for task_id, task_ws_id in tasks_parents:
        stmt = sa.update(Task).where(Task.task_id == task_id).values(task_ws_id=int(task_ws_id))
        conn.execute(stmt)


    # ### end Alembic commands ###


def downgrade():
    # # ### commands auto generated by Alembic - please adjust! ###
    # pass
    tasks_parents_stmt = sa.select(Task.task_id, Task.task_ws_id)
    tasks_parents = conn.execute(tasks_parents_stmt).fetchall()

    op.drop_column("tasks", "task_ws_id")
    with op.batch_alter_table("tasks") as batch_op:
        batch_op.add_column(sa.Column("task_ws_id", sa.String(15), nullable=True))

    for task_id, task_ws_id in tasks_parents:
        stmt = sa.update(Task).where(Task.task_id == task_id).values(task_ws_id=str(task_ws_id))
        conn.execute(stmt)
    # ### end Alembic commands ###
