"""add russian status name

Revision ID: 527bf6f90e29
Revises: 0b53df33a4db
Create Date: 2022-04-21 16:40:30.853534

"""
from alembic import op
import sqlalchemy as sa
from app.db.structure_of_db import session
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '527bf6f90e29'
down_revision = '0b53df33a4db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statuses', sa.Column('status_ru_name', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statuses', 'status_ru_name')

    # ### end Alembic commands ###
