"""add_user_image

Revision ID: 5f0c104ab39a
Revises: d183981b007b
Create Date: 2022-05-16 15:18:04.644182

"""
from alembic import op
import sqlalchemy as sa
from app.db.structure_of_db import session
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5f0c104ab39a'
down_revision = 'd183981b007b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_image', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_image')
    # ### end Alembic commands ###
