"""new project columns

Revision ID: 92b621266fa8
Revises: 49468fded71c
Create Date: 2022-03-22 09:00:29.426771

"""
from alembic import op
import sqlalchemy as sa
from app.db.structure_of_db import session


# revision identifiers, used by Alembic.
revision = '92b621266fa8'
down_revision = '49468fded71c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_status', sa.String(length=15)))
    op.add_column('projects', sa.Column('project_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'project_description')
    op.drop_column('projects', 'project_status')
    # ### end Alembic commands ###
