"""to actual

Revision ID: b444fd4ee703
Revises: c3a6901de8c7
Create Date: 2022-03-15 14:46:00.692698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b444fd4ee703'
down_revision = 'c3a6901de8c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_bookmark', 'ub_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_bookmark', sa.Column('ub_id', sa.INTEGER(), autoincrement=True, nullable=True))
    # ### end Alembic commands ###
