"""projects name unique

Revision ID: e90954862b06
Revises: 82ecefc45915
Create Date: 2022-03-30 17:37:42.728449

"""
from alembic import op
import sqlalchemy as sa
from app.db.structure_of_db import session


# revision identifiers, used by Alembic.
revision = 'e90954862b06'
down_revision = '82ecefc45915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("projects_project_name_unique", 'projects', ['project_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("projects_project_name_unique", 'projects', type_='unique')
    # ### end Alembic commands ###
